### ISSUE TITLE
Hardware options not fully integrated into code

### ISSUE THREAD

**Issue by snmohan** [ermtl/Open-Source-Ventilator#17]
There are variables in the latest release that rely on the availability of certain hardware (the use of #ifdef is not comprehensive). 

For example: 
keys[maxBtn] should only be defined when TM1638Keyboard is defined
disp[dispBufferLength] only when TM1638Display

**Comment by ermtl** [comment]
As you'll see in the 0.20 version that also allow the use of another type of keyboard keys[maxBtn]  is used by either type of keyboard.
Same for disp[dispBufferLength] that, since V0.17 is also used for the 2 lines x 16 characters display.
That's why the conditional defines are not limited to TM1638.
