### ISSUE TITLE
Using potentiometers for PEEP, TIDAL_VOL, and RESP_RATE

### ISSUE THREAD

**Issue by billygts15** [ermtl/Open-Source-Ventilator#28]
I'm trying to get the potentiometers working for the PEEP, TIDAL_VOL, and RESP_RATE, but need a little help defining the pins.

**Comment by ermtl** [comment]
The MIT design uses them, but the risk for accidental moves is important and they needed to add a confirmation button, so that might not be as easy and intuitive to use as it seems.  If you want to add them, you can use pins A0,A2,A3 for the 3 potentiometers as they are currently unused. 
You can read them at the same place as analogReadKeys();
When they are moved, you can change menuItem so that the right item is displayed then call setDisplayMenu. If you add that and want it merged, please make sure the changes use conditional compilation so that the option can be activated or not.

**Comment by billygts15** [comment]
Thanks.
